"""Add user_id to Reservation

Revision ID: a745e22797e6
Revises: f98c8e13978f
Create Date: 2023-09-09 02:01:11.073769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a745e22797e6'
down_revision = 'f98c8e13978f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetingroom', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_meetingroom_name'), ['name'])

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reservation_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reservation_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('meetingroom', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_meetingroom_name'), type_='unique')

    # ### end Alembic commands ###
